const {app,BrowserWindow,WebContentsView,ipcMain,session}=require("electron"); const path=require("path"); const {enablePrivacy}=require("./src/privacy"); const migration=require("./src/migration");
let win,tabs=[],activeId=0,nextId=1,ses; const shellWidth=296,toolbarHeight=64;
const clean=t=>({id:t.id,title:t.title,url:t.url,loading:t.loading}); const emit=()=>win?.webContents.send("tabs:state",{tabs:tabs.map(clean),activeId});
function layout(){if(!win)return;const b=win.getContentBounds();for(const t of tabs)t.view.setBounds(t.id===activeId&&t.url!=="veyra://home"?{x:shellWidth,y:toolbarHeight,width:Math.max(1,b.width-shellWidth),height:Math.max(1,b.height-toolbarHeight)}:{x:0,y:0,width:0,height:0});}
function wire(t){const wc=t.view.webContents;wc.on("page-title-updated",(_e,v)=>{t.title=v;emit()});wc.on("did-start-loading",()=>{t.loading=true;emit()});wc.on("did-stop-loading",()=>{t.loading=false;t.url=wc.getURL()||t.url;emit()});wc.on("did-navigate",(_e,u)=>{t.url=u;emit()});wc.setWindowOpenHandler(({url})=>{createTab(url);return{action:"deny"}});}
function createTab(url="veyra://home"){const view=new WebContentsView({webPreferences:{partition:"persist:veyra",contextIsolation:true,sandbox:true,nodeIntegration:false}}),t={id:nextId++,title:"New Tab",url,loading:false,view};tabs.push(t);win.contentView.addChildView(view);wire(t);activeId=t.id;if(url!=="veyra://home")view.webContents.loadURL(url);layout();emit();return t;}
function switchTab(id){if(tabs.some(t=>t.id===id)){activeId=id;layout();emit()}} function closeTab(id){const i=tabs.findIndex(t=>t.id===id);if(i<0)return;const[t]=tabs.splice(i,1);win.contentView.removeChildView(t.view);t.view.webContents.close();if(activeId===id)activeId=tabs.at(Math.max(0,i-1))?.id||0;if(!tabs.length)createTab();layout();emit();}
function target(){return tabs.find(t=>t.id===activeId)} function go(raw){const t=target();if(!t)return;const url=/^[a-zA-Z][\w+.-]*:\/\//.test(raw)?raw:/^[\w.-]+\.[a-z]{2,}(\/.*)?$/i.test(raw)?"https://"+raw:"https://search.brave.com/search?q="+encodeURIComponent(raw);t.url=url;t.view.webContents.loadURL(url);layout();emit();}
app.whenReady().then(async()=>{ses=session.fromPartition("persist:veyra");await enablePrivacy(ses);win=new BrowserWindow({width:1500,height:930,minWidth:980,minHeight:650,titleBarStyle:"hidden",backgroundColor:"#090b10",webPreferences:{preload:path.join(__dirname,"src/preload.js"),contextIsolation:true,sandbox:true,nodeIntegration:false}});await win.loadFile(path.join(__dirname,"src/index.html"));createTab();win.on("resize",layout);if(process.argv.includes("--dev"))win.webContents.openDevTools({mode:"detach"});});
ipcMain.handle("tabs:list",()=>({tabs:tabs.map(clean),activeId}));ipcMain.on("tab:new",()=>createTab());ipcMain.on("tab:switch",(_e,id)=>switchTab(id));ipcMain.on("tab:close",(_e,id)=>closeTab(id));ipcMain.on("nav:go",(_e,v)=>go(v));ipcMain.on("nav:back",()=>target()?.view.webContents.goBack());ipcMain.on("nav:forward",()=>target()?.view.webContents.goForward());ipcMain.on("nav:reload",()=>target()?.view.webContents.reload());ipcMain.handle("migration:scan",()=>migration.scan());ipcMain.handle("migration:import",(_e,s)=>migration.importBookmarks(s,app.getPath("userData")));
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});